### ISSUE TITLE
Fails to boot after deploy due to `undefined method `new' for Statsd:Module`

### ISSUE THREAD

**Issue by xavriley** [heroku/ruby-getting-started#24]
Steps to reproduce:

1) `git clone https://github.com/heroku/ruby-getting-started.git`
2) `heroku create`
3) `git push heroku master`
4) `heroku open # App crashes with H10 error`

Stack trace of crash:

```
2017-07-25T09:12:18.415329+00:00 heroku[web.1]: Starting process with command `bundle exec puma -C config/puma.rb`
2017-07-25T09:12:20.067968+00:00 app[web.1]: [4] Puma starting in cluster mode...
2017-07-25T09:12:20.067981+00:00 app[web.1]: [4] * Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
2017-07-25T09:12:20.067983+00:00 app[web.1]: [4] * Min threads: 5, max threads: 5
2017-07-25T09:12:20.068007+00:00 app[web.1]: [4] * Environment: production
2017-07-25T09:12:20.068009+00:00 app[web.1]: [4] * Process workers: 2
2017-07-25T09:12:20.068025+00:00 app[web.1]: [4] * Preloading application
2017-07-25T09:12:20.807896+00:00 app[web.1]: [4] ! Unable to load application: NoMethodError: undefined method `new' for Statsd:Module
2017-07-25T09:12:20.808084+00:00 app[web.1]: NoMethodError: undefined method `new' for Statsd:Module
2017-07-25T09:12:20.807963+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.4.0/bin/puma)
2017-07-25T09:12:20.808085+00:00 app[web.1]:   /app/config/application.rb:15:in `<class:Application>'
2017-07-25T09:12:20.808086+00:00 app[web.1]:   /app/config/application.rb:14:in `<module:RubyGettingStarted>'
2017-07-25T09:12:20.808086+00:00 app[web.1]:   /app/config/application.rb:13:in `<top (required)>'
2017-07-25T09:12:20.808087+00:00 app[web.1]:   /app/config/environment.rb:2:in `require'
2017-07-25T09:12:20.808087+00:00 app[web.1]:   /app/config/environment.rb:2:in `<top (required)>'
2017-07-25T09:12:20.808088+00:00 app[web.1]:   config.ru:3:in `require'
2017-07-25T09:12:20.808088+00:00 app[web.1]:   config.ru:3:in `block in <main>'
2017-07-25T09:12:20.808089+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
2017-07-25T09:12:20.808090+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
2017-07-25T09:12:20.808090+00:00 app[web.1]:   config.ru:in `new'
2017-07-25T09:12:20.808090+00:00 app[web.1]:   config.ru:in `<main>'
2017-07-25T09:12:20.808091+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/builder.rb:49:in `eval'
2017-07-25T09:12:20.808091+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/builder.rb:49:in `new_from_string'
2017-07-25T09:12:20.808092+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.5/lib/rack/builder.rb:40:in `parse_file'
2017-07-25T09:12:20.808092+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/configuration.rb:313:in `load_rackup'
2017-07-25T09:12:20.808093+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/configuration.rb:242:in `app'
2017-07-25T09:12:20.808093+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/runner.rb:138:in `load_and_bind'
2017-07-25T09:12:20.808093+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/cluster.rb:391:in `run'
2017-07-25T09:12:20.808094+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/cli.rb:77:in `run'
2017-07-25T09:12:20.808094+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/lib/puma/launcher.rb:172:in `run'
2017-07-25T09:12:20.808095+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/gems/puma-3.8.2/bin/puma:10:in `<top (required)>'
2017-07-25T09:12:20.808095+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/bin/puma:22:in `<top (required)>'
2017-07-25T09:12:20.808095+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.4.0/bin/puma:22:in `load'
2017-07-25T09:12:20.925543+00:00 heroku[web.1]: Process exited with status 1
2017-07-25T09:12:20.937365+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by nxnxnx** [comment]
Got the same problem when starting up the app. The only way to get around it is to comment out
` config.trashed.statsd = Statsd.new('localhost', ENV["PORT"]) if ENV["PORT"]` (line 15) on config/application.rb
